### ISSUE TITLE
Getting numPendingQueries value always 0 on React Native

### ISSUE THREAD

**Issue by borasumer** [molindo/react-apollo-network-status#44]
Hi, not even sure if it is because React Native, but for some reason getting this status all the time, not sure what I am missing.
```
status: Object {
  "mutationError": undefined,
  "numPendingMutations": 0,
  "numPendingQueries": 0,
  "queryError": undefined,
}
```

This is also my linking setup for Apollo client

`const { link } = createNetworkStatusNotifier();`

```
const authLink = setContext(async (_, { headers }) => {
  const token = await SecureStore.getItemAsync('accessToken');
  return {
    headers: {
      ...headers,
      authorization: token && `${token}`,
    },
  };
});

```

```
const client = new ApolloClient({
  link: authLink.concat(link.concat(httpLink)),
  cache: new InMemoryCache(),
});

```

**Comment by borasumer** [comment]
Yeah I think this is an apollo version issue. I am using 2.6.10. Which latest version of this library does support apollo 2.6.10?
Thanks

**Comment by amannn** [comment]
Hi @borasumer,

right, as you're saying this looks like an issue with the Apollo version you're using. Please have a look at [the changelog](https://github.com/molindo/react-apollo-network-status/blob/master/CHANGELOG.md) to see which version of this library is supported for which Apollo version.

Please also note that older versions might have bugs that are already resolved and not all the latest features are supported. Ideally you'd upgrade both Apollo and this library to the latest version.

I'll close this for now, but please let me know if you have any issues with the latest version.

**Comment by borasumer** [comment]
Hi @amannn, I have updated both apollo-client and this library to their latest versions but still getting this value as 0. Not sure what I am missing, again I am using React Native on Expo, wonder if that could create a limitation, I doubt though.

**Comment by amannn** [comment]
Hmm, interesting. Maybe you're seeing this issue? https://github.com/molindo/react-apollo-network-status/issues/19

Otherwise I don't really know what's causing this. React Native should work equally well, since this library only integrates with Apollo Client itself and doesn't access any platform features like `fetch`.
